### ISSUE TITLE
why doesn't it work with the last version of Clion?

### ISSUE THREAD

**Issue by Skorpionos** [JenoDK/bracket-selection#1]
Incompatible with the current Clion version (2018.3.1)...

**Comment by genseric** [comment]
+1, an update would be nice.

**Comment by JenoDK** [comment]
I'll have a look at it. Feel free to submit a PR if you know what's wrong.

**Comment by JenoDK** [comment]
I updated the plugin to be compatible with the most recent 2018.3.x versions of all products.
See this list:
![image 9](https://user-images.githubusercontent.com/11025460/52067026-ff89c400-2579-11e9-81ac-786115d0682a.png)

**Comment by JenoDK** [comment]
This is available in the 1.2 version (currently pending Jetbrains review https://plugins.jetbrains.com/plugin/11322-bracket-selection)

**Comment by Skorpionos** [comment]
thanks for update!
