### ISSUE TITLE
Add support for 2021.x versions

### ISSUE THREAD

**Issue by vobruba-martin** [JenoDK/bracket-selection#10]
For now I've updated `bracket-selection-1.6.1.jar:/META-INF/plugin.xml` file:
```xml
  <idea-version since-build="172" until-build="203.*"/>
```
to
```xml
  <idea-version since-build="172" until-build="211.*"/>
```

Plugin is now working but I guess there may be some side effects.

**Comment by JenoDK** [comment]
I will update the plugin, it's something that needs to happen every time Jetbrains brings out new builds
