### ISSUE TITLE
possible to make this with just a mouse double/triple click? or say when mouse double clicked with a modifier alt/ctrl etc key?

### ISSUE THREAD

**Issue by yakrider** [JenoDK/bracket-selection#2]
the common use case of selecting inside brackets is often by the mouse, that would make it a lot more usable, and similar to say eclipse and other IDEs.. how difficult would it be to support something like that?

**Comment by JenoDK** [comment]
Hi @yakrider , yes that was my initial intention for this plugin but I did not immediately find how to map a plugin action on a double/triple click. It is on the roadmap though so I will definitely look into it again at one point.

Feel free if you're able to try it out yourself and contribute this change.

**Comment by JenoDK** [comment]
Hi @yakrider , this has been implemented in the 1.3 update.
In that version by default the shortcut is _hold alt_ -> _left double click_
So I will close this.
