### ISSUE TITLE
QOL - select between quotes

### ISSUE THREAD

**Issue by JenoDK** [JenoDK/bracket-selection#5]

**Comment by j-a-s-o-n-g** [comment]
Any update on this? I would really like this to be implemented. 👍

**Comment by j-a-s-o-n-g** [comment]
I was able to connect with a plugin developer and this functionality has been built into https://plugins.jetbrains.com/plugin/16252-codebuddy "Select between typing pairs". Please show your support for Samuel Rizzo for this LONG AWAITED FEATURE!

**Comment by JenoDK** [comment]
Is added in version 1.7
