### ISSUE TITLE
No selection made in Rider

### ISSUE THREAD

**Issue by nicchristeller** [JenoDK/bracket-selection#9]
I'm using JetBrains Rider 2020.3.

When executing any of the actions provided, no selection is made - in fact nothing at all visibly happens. 

Is Rider for some reason not supported?

**Comment by JenoDK** [comment]
Could it be that the keybind is being used by something else?
See https://github.com/JenoDK/bracket-selection/issues/8 for more info.

**Comment by nicchristeller** [comment]
Unfortunately no. Even calling the action explicitly from "Find Actions"
doesn't do anything 😔

**Comment by JenoDK** [comment]
I updated version compatibility with 2021 builds, I tried again to run the plugin on a 2020.3 build but had no issues so I'll close this.

**Comment by nicchristeller** [comment]
Interestingly, Rider 2021.2.1 (212.5080.71) claims to be incompatible:
![image](https://user-images.githubusercontent.com/21079106/135538533-4d93a23b-bc6d-4a53-97e3-433e74956ecd.png)

I installed an older version, 2020.3.4 (203.7717.10) which accepts the plugin, but still doesn't appear to work. In the below gif, I try to execute "Complete bracket selection" both from the actions menu and from keyboard shortcut. Please let me know if I'm missing something, or I can help debug further.
![recording](https://user-images.githubusercontent.com/21079106/135538678-b32050a3-6137-4ec0-8250-981e1b1cf695.gif)

**Comment by JenoDK** [comment]
Hi @nicchristeller 

I was able to install the 1.7.0 plugin version for Rider 2021.2.1
![image](https://user-images.githubusercontent.com/11025460/135888553-03ff846b-cdeb-4824-8b1d-d4882b4ef06f.png)

But once installed I indeed noticed it did not work for C# files for example.
I added C# support in 1.7.1 (currently undergoing Jetbrains validation so should be available soon)

commit: https://github.com/JenoDK/bracket-selection/commit/100a5da63a3cf794d34c735e20b35e4a6099d86e

**Comment by nicchristeller** [comment]
Thank you!
